name: AI Crypto Alerts (Every 30 Minutes)

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  run-alerts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy pandas scikit-learn requests joblib

      - name: Run AI alert script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: |
          mkdir -p artifacts
          timestamp=$(date -u +"%Y%m%d_%H%M%S")
          python crypto_ai_alert_v4.py | tee artifacts/alerts_$timestamp.log

      - name: Upload alert artifacts
        uses: actions/upload-artifact@v4
        with:
          name: crypto_alert_logs
          path: artifacts/
